[build]
  publish = "." # This tells Netlify to serve files from the root of your repository
  functions = "netlify/functions" # This specifies the directory where your Netlify Functions are located

[functions]
  node_bundler = "esbuild" # Use esbuild for faster function bundling
